begin;
INSERT INTO exames(id, tipo, dataex, idp) VALUES (0, 'Raio-X', '2019-04-15', 1);
INSERT INTO exames(id, tipo, dataex, idp) VALUES (1, 'Ultrassom', '2018-08-22', 2);
INSERT INTO exames(id, tipo, idp) VALUES (2, 'Tomografia', 3);
INSERT INTO exames(id, tipo, idp) VALUES (3, 'Laudo', 4);
INSERT INTO exames(id, tipo, idp) VALUES (4, 'Laudo', 5);
INSERT INTO exames(id, tipo, idp) VALUES (5, 'Tomografia', 6);
INSERT INTO exames(id, tipo, idp) VALUES (6, 'Ultrassom', 7);
INSERT INTO exames(id, tipo, idp) VALUES (7, 'Raio-X', 8);
INSERT INTO exames(id, tipo, dataex, idp) VALUES (8, 'Laudo', '2020-02-10', 9);
INSERT INTO exames(id, tipo, dataex, idp) VALUES (9, 'Tomografia', '2018-11-30', 0);
INSERT INTO exames(id, tipo, idp) VALUES (10, 'Laudo', 1);
INSERT INTO exames(id, tipo, idp) VALUES (11, 'Raio-X', 2);
INSERT INTO exames(id, tipo, idp) VALUES (12, 'Ultrassom', 3);
INSERT INTO exames(id, tipo, idp) VALUES (13, 'Tomografia', 4);
INSERT INTO exames(id, tipo, dataex, idp) VALUES (14, 'Ultrassom', '2019-07-18', 5);
INSERT INTO exames(id, tipo, idp) VALUES (15, 'Raio-X', 6);
INSERT INTO exames(id, tipo, dataex, idp) VALUES (16, 'Tomografia', '2021-01-05', 7);
INSERT INTO exames(id, tipo, idp) VALUES (17, 'Laudo', 8);
INSERT INTO exames(id, tipo, idp) VALUES (18, 'Laudo', 9);
INSERT INTO exames(id, tipo, dataex, idp) VALUES (19, 'Raio-X', '2020-09-14', 0);